name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30bcea18c53dd4773d8d85502cbc240757fb951a5de0afb9d1ee5e529e1bb801"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
